
version: 2

models:
  - name: stg_team
    description: "Staging model for NBA teams"
    columns:
      - name: team_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: stg_player
    description: "Staging model for NBA players"
    columns:
      - name: player_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: stg_game
    description: "Staging model for NBA games"
    columns:
      - name: game_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
