
version: 2

models:
  - name: stg_team
    description: "Staging model for NBA teams"
    columns:
      - name: airbyte_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: stg_player
    description: "Staging model for NBA players"
    columns:
      - name: airbyte_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: stg_game
    description: "Staging model for NBA games"
    columns:
      - name: airbyte_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: stg_box_score
    description: "Staging model for NBA box_scores"
    columns:
      - name: airbyte_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
